image: eclipse-temurin:17-jdk-jammy
before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget unzip
  - chmod +x ./gradlew

stages:
  - build
  - package

build:
  stage: build
  timeout: 20 minutes
  script:
    - echo "Start building app"
    - ./gradlew build :jar
    - echo "Finish building app"
    - echo "Make output dir"
    - mkdir -p build_output
    - echo "Copy jar"
    - cp build/libs/*.jar build_output/
    - echo "Publish output dir"
  artifacts:
    paths:
      - build_output/
    expire_in: 20 minutes
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always

package_zip:
  stage: package
  dependencies:
    - build
  needs: ["build"]
  script:
    - echo "Create target directory"
    - mkdir -p db_scheduler_executor
    - echo "Copy files to target directory"
    - cp ./build_output/*.jar db_scheduler_executor/
    - cp ./killScheduler.sh db_scheduler_executor/
    - cp ./runScheduler.sh db_scheduler_executor/
    - cp ./src/main/resources/app.properties db_scheduler_executor/
    - echo "Zip files..."
    - zip -r db_scheduler_executor.zip db_scheduler_executor
    - echo "Publish artifacts"
  artifacts:
    paths:
      - db_scheduler_executor.zip
    when: on_success
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always